# Generated by Django 5.0.3 on 2024-08-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituto', '0003_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='dni',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
