# Generated by Django 5.0.3 on 2024-08-28 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituto', '0004_alter_estudiante_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='codigo',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
